name: Tests for `ddev-civicrm-cli-tools`

on:
  pull_request:
    paths-ignore:
      - "**.md"

  push:
    branches: [main]
    paths-ignore:
      - "**.md"

  schedule:
    - cron: "25 08 * * *"

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  stable:
    name: tests (stable)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: stable
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ github.repository }}
          addon_ref: ${{ github.ref }}

  head:
    name: tests (HEAD canary)
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true

    steps:
      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: HEAD
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ github.repository }}
          addon_ref: ${{ github.ref }}
